name: Build Allinone

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                component: [all]
        steps:
            - uses: actions/checkout@v4
            - uses: docker/setup-qemu-action@v3
            - uses: docker/setup-buildx-action@v3
            - name: Get Version
              run: |
                echo "version=$(basename ${GITHUB_REF})" >> $GITHUB_ENV

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: wojiushixiaobai
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Image
              uses: docker/build-push-action@v5
              with:
                    context: ./allinone
                    file: Dockerfile
                    platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
                    push: true
                    tags: |
                      wojiushixiaobai/jms_${{ matrix.component }}:${{ env.version }}
                      wojiushixiaobai/jms_${{ matrix.component }}:latest
                      ghcr.io/wojiushixiaobai/jms_${{ matrix.component }}:${{ env.version }}
                      ghcr.io/wojiushixiaobai/jms_${{ matrix.component }}:latest